#!/bin/sh

# adicionando opções padrões
alias cp='cp -iv' \
      mv='mv -iv' \
      rm='rm -Iv' \
      mkdir='mkdir -pv' \
      ls="ls -phN --color=auto --group-directories-first" \
      grep="grep --color=auto" \
      diff="diff --color=auto" \
      less="less -R"

# abreviações de comandos longos
alias xb='xbacklight' \
      xrb='xrandr --output VGA1 --brightness' \
      sx="startx ${HOME}/.config/X11/xinitrc" \
      p='doas pacman' \
      mci='doas make clean install' \
      gc='git commit' \
      gpom='git push origin master' \
      gitu='git add . && git commit -m "update" && git push origin'

# preguiça
alias v='nvim' \
