#!/bin/sh

# FUNÇÕES -----------------------------------------------------------------------

gd() {
	clear
	case "$1" in
		*/) DIR=$(vis-open -t "$1");;
		*) DIR=$(vis-find -d "$@")/
	esac
	clear; cd "${DIR%/*}"
}

v() {
	clear
	CHOICE=$(vis-find . "$1")
	clear
	[ -n "$CHOICE" ] && vis "$CHOICE"
}

m() { dmenu_path | grep "^$1" | vis-menu -p "manual:" | xargs -r man; }

# ALIASES -----------------------------------------------------------------------

# adicionando opções padrões
alias cp='cp -iv' \
      mv='mv -iv' \
      rm='rm -Iv' \
      mkdir='mkdir -pv' \
      ls="ls -phCN --color=auto --group-directories-first" \
      grep="grep --color=auto --exclude-dir='.git' -I" \
      diff="diff --color=auto"

# abreviações de comandos longos
alias xrb='xrandr --output VGA1 --brightness' \
      p='doas pacman' \
      mci='doas make clean install' \
      Gc='git commit' \
      GC='git clone --depth 1' \
      Gd='git diff' \
      Gl='git log -p' \
      Gs='git status' \
      Gb='git checkout' \
      Gpom='git push origin master' \
      Gpfb='git push fork mybuild'

# preguiça
alias ..='cd ..' \
	  +x='chmod +x' \
      vf='vis-find'
