#!/bin/sh

# FUNÇÕES -----------------------------------------------------------------------

# encontrar arquivos e abrir no editor
v() {
	CHOICE=$(vis-find)
	[ -f "$CHOICE" ] && vis "$CHOICE"
	echo
}

# lista programas com dmenu_path e usa a saída para o programa 'man'
m() {
	local PROGRAM="$(dmenu_path | grep ^$1 | vis-menu -p 'manual:')" && \
	man "$PROGRAM" 
	echo
}

# encontrar e entrar em diretórios
gd() {
	DIR=$(vis-find --dir "$@")
	[ -d "$DIR" ] && cd "$DIR"
	echo
}

# ALIASES -----------------------------------------------------------------------

# adicionando opções padrões
alias cp='cp -iv' \
      mv='mv -iv' \
      rm='rm -Iv' \
      mkdir='mkdir -pv' \
      ls="ls -phN --color=auto --group-directories-first" \
      grep="grep --color=auto --exclude-dir='.git' -I" \
      diff="diff --color=auto"

# abreviações de comandos longos
alias xb='xbacklight' \
      xrb='xrandr --output VGA1 --brightness' \
      p='doas pacman' \
      mci='doas make clean install' \
      gc='git commit' \
      gs='git status' \
      gb='git checkout' \
      gpom='git push origin master' \
      gpfb='git push fork build' \
      gitu='git add . && git commit -a && git push origin'

# preguiça
alias ..='cd ..' \
      vf='vis-find'
