#!/bin/sh
set -a

# programas padrões
TERMINAL='st'
EDITOR='vis'

# XDG
XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_CACHE_HOME="$HOME/.local/var/cache"

# X11
XINITRC="$HOME/.config/X11/xinitrc"
XAUTHORITY="$HOME/.config/X11/Xauthority"
alias sx="startx $XINITRC"

# shell
ZDOTDIR="$XDG_CONFIG_HOME/shell"
INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
ENV="$XDG_CONFIG_HOME/shell/shinit"

# outros arquivos de configuração
R_ENVIRON_USER="$XDG_CONFIG_HOME/R/Renviron"
GNUPGHOME="$XDG_CONFIG_HOME/gnupg"

# less(1)
LESSHISTFILE="-"
LESS_TERMCAP_mb="$(printf '%b' '\033[1;31m')"
LESS_TERMCAP_md="$(printf '%b' '\033[1;36m')"
LESS_TERMCAP_me="$(printf '%b' '\033[0m')"
LESS_TERMCAP_so="$(printf '%b' '\033[01;44;33m')"
LESS_TERMCAP_se="$(printf '%b' '\033[0m')"
LESS_TERMCAP_us="$(printf '%b' '\033[1;32m')"
LESS_TERMCAP_ue="$(printf '%b' '\033[0m')"
