#!/bin/sh

# programas padrões
TERMINAL='st'
EDITOR='vis'
BROWSER="${HOME}/.local/bin/vimb-tabbed"
FILEMANAGER='lf'
READER="{HOME}/.local/bin/zathura-tabbed"

export TERMINAL EDITOR BROWSER FILEMANAGER READER

# arquivos de configuração
XDG_CONFIG_HOME="$HOME/.config"
ZDOTDIR="$XDG_CONFIG_HOME/shell"
XINITRC="${HOME}/.config/X11/xinitrc"
XAUTHORITY="${HOME}/.config/X11/Xauthority"
XDG_DATA_HOME="$HOME/.local/share"
R_ENVIRON_USER="${XDG_CONFIG_HOME}/R/Renviron"
GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
INPUTRC="${XDG_CONFIG_HOME}/shell/inputrc"

export XDG_CONFIG_HOME ZDOTDIR XINITRC XAUTHORITY XDG_DATA_HOME R_ENVIRON_USER \
	GNUPGHOME INPUTRC

# histórico e cache
XDG_CACHE_HOME="${XDG_DATA_HOME}/cache"
LESSHISTFILE="${XDG_CACHE_HOME}/lesshist"

export XDG_CACHE_HOME HISTFILE HISTSIZE LESSHISTFILE

# cores dos manuais (less)
LESS_TERMCAP_mb="$(printf '%b' '\033[1;31m')"
LESS_TERMCAP_md="$(printf '%b' '\033[1;36m')"
LESS_TERMCAP_me="$(printf '%b' '\033[0m')"
LESS_TERMCAP_so="$(printf '%b' '\033[01;44;33m')"
LESS_TERMCAP_se="$(printf '%b' '\033[0m')"
LESS_TERMCAP_us="$(printf '%b' '\033[1;32m')"
LESS_TERMCAP_ue="$(printf '%b' '\033[0m')"
export LESS_TERMCAP_mb LESS_TERMCAP_md LESS_TERMCAP_me LESS_TERMCAP_se \
	LESS_TERMCAP_so LESS_TERMCAP_ue LESS_TERMCAP_us

# inicializar o servidor X
alias sx="startx $XINITRC"

# script de inicialização genérico para shells interativos
ENV="${XDG_CONFIG_HOME}/shell/.shinit"
export ENV
