#!/bin/sh
# inicialização do Xorg

xbacklight -set 12 &
xset r rate 300 50 &
xcompmgr &

unclutter &
xwallpaper --output LVDS1 --zoom /home/jpgg/Imagem/colecao-papel-de-parede/minas-gerais-brazil-nature.jpg &
#feh --randomize --no-fehbg --bg-fill ~/Imagem/colecao-papel-de-parede/* &

slstatus &
exec dwm
